# Generated by Django 2.2.2 on 2019-06-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('tech', 'tech'), ('comics', 'comics'), ('games', 'games'), ('food', 'food'), ('music', 'music')], default='tech', max_length=6),
        ),
    ]
